spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: mircoservicecloud-config-wool-dev
---
spring:
  profiles: test
  application:
    name: mircoservicecloud-config-wool-test
# 请保存为UTF-8格式