spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: mircoservicecloud-config-eureka
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false  #当前得eureka-server自己不注册进服务列表中
    fetch-registry: false        #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
spring:
  profiles: test
  application:
    name: mircoservicecloud-config-eureka
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false  #当前得eureka-server自己不注册进服务列表中
    fetch-registry: false        #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/